#!/usr/bin/env bash
# Sandbox entrypoint: runs as PID 1 inside the Docker Sandbox VM.
#
# Looks for sandbox-init.sh in $WORKSPACE_DIR (set by Docker Sandbox)
# and runs it as the agent user. If no init script exists yet (sandbox
# not fully configured), falls back to sleep infinity.
#
# The init script is generated by `sandbox start` and ends with
# `exec openclaw gateway`, which becomes PID 1 and keeps the VM alive.

set -e

# CRITICAL: Set HOME before any code runs. Without this, root processes
# create /root/.openclaw and agent processes use /home/agent/.openclaw,
# splitting auth tokens between two locations.
export HOME=/home/agent

WORKSPACE="${WORKSPACE_DIR:-}"

if [ -z "$WORKSPACE" ] || [ ! -f "$WORKSPACE/sandbox-init.sh" ]; then
    echo "[entrypoint] No sandbox-init.sh in WORKSPACE_DIR=$WORKSPACE"
    echo "[entrypoint] Run 'sandbox start <name>' to configure, then restart."
    exec sleep infinity
fi

echo "[entrypoint] Workspace: $WORKSPACE"

# Root setup (link configs, copy auth — needs root)
if [ -f "$WORKSPACE/sandbox-root-setup.sh" ]; then
    echo "[entrypoint] Running root setup..."
    bash "$WORKSPACE/sandbox-root-setup.sh"
fi

# Ensure /tmp is writable by agent (OpenClaw jiti cache)
chmod 1777 /tmp
rm -rf /tmp/jiti
mkdir -p /tmp/jiti
chown agent:agent /tmp/jiti

# Start OpenClaw as agent user
# The init script sources .env, sets NODE_OPTIONS, and ends with
# `exec openclaw gateway` which replaces this process.
echo "[entrypoint] Starting OpenClaw..."
exec su agent -c "export HOME=/home/agent && bash $WORKSPACE/sandbox-init.sh"
